# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: categories.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'categories.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61tegories.proto\x12\ncategories\"&\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"\x17\n\x15ListCategoriesRequest\"B\n\x16ListCategoriesResponse\x12(\n\ncategories\x18\x01 \x03(\x0b\x32\x14.categories.Category2l\n\x11\x43\x61tegoriesService\x12W\n\x0eListCategories\x12!.categories.ListCategoriesRequest\x1a\".categories.ListCategoriesResponseB\x1e\n\x1a\x63om.empuje.grpc.categoriesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'categories_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.empuje.grpc.categoriesP\001'
  _globals['_CATEGORY']._serialized_start=32
  _globals['_CATEGORY']._serialized_end=70
  _globals['_LISTCATEGORIESREQUEST']._serialized_start=72
  _globals['_LISTCATEGORIESREQUEST']._serialized_end=95
  _globals['_LISTCATEGORIESRESPONSE']._serialized_start=97
  _globals['_LISTCATEGORIESRESPONSE']._serialized_end=163
  _globals['_CATEGORIESSERVICE']._serialized_start=165
  _globals['_CATEGORIESSERVICE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
