# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import donations_pb2 as donations__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in donations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDonation = channel.unary_unary(
                '/donations.DonationsService/CreateDonation',
                request_serializer=donations__pb2.CreateDonationRequest.SerializeToString,
                response_deserializer=donations__pb2.CreateDonationResponse.FromString,
                _registered_method=True)
        self.GetDonation = channel.unary_unary(
                '/donations.DonationsService/GetDonation',
                request_serializer=donations__pb2.GetDonationRequest.SerializeToString,
                response_deserializer=donations__pb2.GetDonationResponse.FromString,
                _registered_method=True)
        self.ListDonations = channel.unary_unary(
                '/donations.DonationsService/ListDonations',
                request_serializer=donations__pb2.ListDonationsRequest.SerializeToString,
                response_deserializer=donations__pb2.ListDonationsResponse.FromString,
                _registered_method=True)
        self.UpdateDonationQty = channel.unary_unary(
                '/donations.DonationsService/UpdateDonationQty',
                request_serializer=donations__pb2.UpdateDonationQtyRequest.SerializeToString,
                response_deserializer=donations__pb2.UpdateDonationQtyResponse.FromString,
                _registered_method=True)
        self.SoftDeleteDonation = channel.unary_unary(
                '/donations.DonationsService/SoftDeleteDonation',
                request_serializer=donations__pb2.SoftDeleteDonationRequest.SerializeToString,
                response_deserializer=donations__pb2.SoftDeleteDonationResponse.FromString,
                _registered_method=True)


class DonationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDonation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDonation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDonations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDonationQty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SoftDeleteDonation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDonation,
                    request_deserializer=donations__pb2.CreateDonationRequest.FromString,
                    response_serializer=donations__pb2.CreateDonationResponse.SerializeToString,
            ),
            'GetDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDonation,
                    request_deserializer=donations__pb2.GetDonationRequest.FromString,
                    response_serializer=donations__pb2.GetDonationResponse.SerializeToString,
            ),
            'ListDonations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDonations,
                    request_deserializer=donations__pb2.ListDonationsRequest.FromString,
                    response_serializer=donations__pb2.ListDonationsResponse.SerializeToString,
            ),
            'UpdateDonationQty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDonationQty,
                    request_deserializer=donations__pb2.UpdateDonationQtyRequest.FromString,
                    response_serializer=donations__pb2.UpdateDonationQtyResponse.SerializeToString,
            ),
            'SoftDeleteDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.SoftDeleteDonation,
                    request_deserializer=donations__pb2.SoftDeleteDonationRequest.FromString,
                    response_serializer=donations__pb2.SoftDeleteDonationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'donations.DonationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('donations.DonationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DonationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonationsService/CreateDonation',
            donations__pb2.CreateDonationRequest.SerializeToString,
            donations__pb2.CreateDonationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonationsService/GetDonation',
            donations__pb2.GetDonationRequest.SerializeToString,
            donations__pb2.GetDonationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDonations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonationsService/ListDonations',
            donations__pb2.ListDonationsRequest.SerializeToString,
            donations__pb2.ListDonationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDonationQty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonationsService/UpdateDonationQty',
            donations__pb2.UpdateDonationQtyRequest.SerializeToString,
            donations__pb2.UpdateDonationQtyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SoftDeleteDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/donations.DonationsService/SoftDeleteDonation',
            donations__pb2.SoftDeleteDonationRequest.SerializeToString,
            donations__pb2.SoftDeleteDonationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
