# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: roles.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'roles.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broles.proto\x12\x05roles\"\"\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"\x12\n\x10ListRolesRequest\"/\n\x11ListRolesResponse\x12\x1a\n\x05roles\x18\x01 \x03(\x0b\x32\x0b.roles.Role2N\n\x0cRolesService\x12>\n\tListRoles\x12\x17.roles.ListRolesRequest\x1a\x18.roles.ListRolesResponseB\x19\n\x15\x63om.empuje.grpc.rolesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roles_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.empuje.grpc.rolesP\001'
  _globals['_ROLE']._serialized_start=22
  _globals['_ROLE']._serialized_end=56
  _globals['_LISTROLESREQUEST']._serialized_start=58
  _globals['_LISTROLESREQUEST']._serialized_end=76
  _globals['_LISTROLESRESPONSE']._serialized_start=78
  _globals['_LISTROLESRESPONSE']._serialized_end=125
  _globals['_ROLESSERVICE']._serialized_start=127
  _globals['_ROLESSERVICE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
