# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x87\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x0e\n\x06rol_id\x18\x07 \x01(\x03\x12\x0e\n\x06\x61\x63tivo\x18\x08 \x01(\x08\"\x8a\x01\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\x10\n\x08telefono\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x0e\n\x06rol_id\x18\x07 \x01(\x03\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"G\n\rLoginResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x19\n\x04user\x18\x03 \x01(\x0b\x32\x0b.users.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\",\n\x0fGetUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"7\n\x10ListUsersRequest\x12\x13\n\x0bonly_active\x18\x01 \x01(\x08\x12\x0e\n\x06rol_id\x18\x02 \x01(\x03\"/\n\x11ListUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User2\xff\x01\n\x0cUsersService\x12\x41\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12\x32\n\x05Login\x12\x13.users.LoginRequest\x1a\x14.users.LoginResponse\x12\x38\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\x12>\n\tListUsers\x12\x17.users.ListUsersRequest\x1a\x18.users.ListUsersResponseB\x19\n\x15\x63om.empuje.grpc.usersP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.empuje.grpc.usersP\001'
  _globals['_USER']._serialized_start=23
  _globals['_USER']._serialized_end=158
  _globals['_CREATEUSERREQUEST']._serialized_start=161
  _globals['_CREATEUSERREQUEST']._serialized_end=299
  _globals['_CREATEUSERRESPONSE']._serialized_start=301
  _globals['_CREATEUSERRESPONSE']._serialized_end=348
  _globals['_LOGINREQUEST']._serialized_start=350
  _globals['_LOGINREQUEST']._serialized_end=400
  _globals['_LOGINRESPONSE']._serialized_start=402
  _globals['_LOGINRESPONSE']._serialized_end=473
  _globals['_GETUSERREQUEST']._serialized_start=475
  _globals['_GETUSERREQUEST']._serialized_end=503
  _globals['_GETUSERRESPONSE']._serialized_start=505
  _globals['_GETUSERRESPONSE']._serialized_end=549
  _globals['_LISTUSERSREQUEST']._serialized_start=551
  _globals['_LISTUSERSREQUEST']._serialized_end=606
  _globals['_LISTUSERSRESPONSE']._serialized_start=608
  _globals['_LISTUSERSRESPONSE']._serialized_end=655
  _globals['_USERSSERVICE']._serialized_start=658
  _globals['_USERSSERVICE']._serialized_end=913
# @@protoc_insertion_point(module_scope)
